// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1LrzTLvZ14upNNMPKals_UNHl-s1WQk',
    appId: '1:544219650132:web:3b41279fdc5eb57974f5c1',
    messagingSenderId: '544219650132',
    projectId: 'notes-9e2f5',
    authDomain: 'notes-9e2f5.firebaseapp.com',
    storageBucket: 'notes-9e2f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEadvXh9Lt3Kurxjx_Gp2pQfoYqVM2hw',
    appId: '1:544219650132:android:45a87dc9f3ac0c3d74f5c1',
    messagingSenderId: '544219650132',
    projectId: 'notes-9e2f5',
    storageBucket: 'notes-9e2f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdrx3MIQq1ojtBIAZk9-GltvL6scrpnGo',
    appId: '1:544219650132:ios:1534fa4af7d7253074f5c1',
    messagingSenderId: '544219650132',
    projectId: 'notes-9e2f5',
    storageBucket: 'notes-9e2f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
